apiVersion: v2
name: persons-finder
description: A Helm chart for Persons Finder Spring Boot application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - persons-finder
  - spring-boot
  - kubernetes
maintainers:
  - name: DevOps Team
home: https://github.com/nightrainbow45/persons-finder-devops
sources:
  - https://github.com/nightrainbow45/persons-finder-devops
