{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "persons-finder.fullname" . }}
  labels:
    {{- include "persons-finder.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "persons-finder.fullname" . }}
  labels:
    {{- include "persons-finder.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "persons-finder.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "persons-finder.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
